// GENERATED by gen_vectors.py -- do not edit.
// arctan(2**-i) in the internal angle format (Q2.15), i = 0 .. 13
localparam iangle_t ATAN_ROM_GEN [14] = '{
  18'sd25736,   // atan(2**-0) = 0.785398163 rad
  18'sd15193,   // atan(2**-1) = 0.463647609 rad
  18'sd8027,   // atan(2**-2) = 0.244978663 rad
  18'sd4075,   // atan(2**-3) = 0.124354995 rad
  18'sd2045,   // atan(2**-4) = 0.062418810 rad
  18'sd1024,   // atan(2**-5) = 0.031239833 rad
  18'sd512,   // atan(2**-6) = 0.015623729 rad
  18'sd256,   // atan(2**-7) = 0.007812341 rad
  18'sd128,   // atan(2**-8) = 0.003906230 rad
  18'sd64,   // atan(2**-9) = 0.001953123 rad
  18'sd32,   // atan(2**-10) = 0.000976562 rad
  18'sd16,   // atan(2**-11) = 0.000488281 rad
  18'sd8,   // atan(2**-12) = 0.000244141 rad
  18'sd4    // atan(2**-13) = 0.000122070 rad
};
