#!/usr/bin/env python3
"""
Generate everything the other testbenches need from the Python golden model.

This one script demonstrates the two build-time couplings described in
Chapter 9:

  (a) *offline vectors* -- a plain text file that any testbench can read,
      with $readmemh, $fscanf, std.textio or an ifstream;

  (b) *generated source* -- a C++ header and a SystemVerilog include file,
      both compiled into their respective testbenches.

Run it from the Makefile, never by hand, so that the generated files can never
be older than the model that produced them.

    python3 gen_vectors.py --n 300 --seed 1 \
        --out ../vectors/cordic_vectors.txt \
        --header ../verilator/cordic_vectors.h \
        --svh ../sv/cordic_vectors.svh \
        --rom ../sv/cordic_atan_rom.svh
"""

import argparse
import math
import os
import random
import sys
import time

import cordic_model as m


# --------------------------------------------------------------------------
# Stimulus
# --------------------------------------------------------------------------
def directed():
    """The angles a random generator will not hit, and the boundaries of the
    coarse-rotation stage."""
    pi_q = m.float_to_q(math.pi, m.QA, m.AW)
    half = pi_q // 2
    out = []
    for th in (0, pi_q, -pi_q, half, -half, half + 1, -half - 1,
               half // 2, -half // 2, 1, -1):
        out.append((m.X0_UNIT, 0, th))
    out.append((0, 0, half))                 # zero vector
    out.append((0, m.X0_UNIT, half))         # start on the y axis
    out.append((6000, -6000, pi_q // 3))
    out.append((-6000, 6000, -pi_q // 3))
    return out


def random_stim(n, seed):
    rng = random.Random(seed)
    pi_q = m.float_to_q(math.pi, m.QA, m.AW)
    return [(rng.randint(-6000, 6000),
             rng.randint(-6000, 6000),
             rng.randint(-pi_q, pi_q)) for _ in range(n)]


def build(n, seed):
    stim = directed() + random_stim(n, seed)
    rows = []
    for x0, y0, th in stim:
        x, y = m.cordic_rot(x0, y0, th)
        rows.append((x0, y0, th, x, y))
    return rows


# --------------------------------------------------------------------------
# (a) the vector file
# --------------------------------------------------------------------------
def write_vectors(path, rows, seed):
    """One transaction per line, 16-bit two's complement in hexadecimal.

    Hexadecimal rather than decimal because $readmemh and $fscanf("%h") both
    want it, and because a hex field has a fixed width, which makes a short
    or corrupted line obvious.  The header records everything needed to
    regenerate the file: without it, a vector file is an unreproducible
    binary blob that happens to be readable.
    """
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as f:
        f.write("# cordic_rot test vectors\n")
        f.write(f"# generated {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"# generator  gen_vectors.py  seed={seed}\n")
        f.write(f"# format     DW={m.DW} QF={m.QF} AW={m.AW} QA={m.QA} "
                f"N={m.N} GL={m.GL} GM={m.GM}\n")
        f.write(f"# count      {len(rows)}\n")
        f.write("# x0    y0    theta xexp  yexp\n")
        for x0, y0, th, x, y in rows:
            f.write(f"{x0 & 0xFFFF:04x}  {y0 & 0xFFFF:04x}  "
                    f"{th & 0xFFFF:04x}  {x & 0xFFFF:04x}  {y & 0xFFFF:04x}\n")
    return len(rows)


# --------------------------------------------------------------------------
# (b) the generated C++ header
# --------------------------------------------------------------------------
def write_header(path, rows, seed):
    with open(path, "w") as f:
        f.write("// GENERATED by gen_vectors.py -- do not edit.\n")
        f.write(f"// seed={seed}  count={len(rows)}\n")
        f.write("#ifndef CORDIC_VECTORS_H_\n#define CORDIC_VECTORS_H_\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("struct CordicVec { int16_t x0, y0, theta, x, y; };\n\n")
        f.write(f"static constexpr unsigned kCordicVecSeed  = {seed};\n")
        f.write(f"static constexpr unsigned kCordicVecCount = {len(rows)};\n\n")
        f.write("static constexpr CordicVec kCordicVectors[] = {\n")
        for x0, y0, th, x, y in rows:
            f.write(f"  {{{x0:6d}, {y0:6d}, {th:6d}, {x:6d}, {y:6d}}},\n")
        f.write("};\n\n#endif  // CORDIC_VECTORS_H_\n")


# --------------------------------------------------------------------------
# (b) the generated SystemVerilog include
# --------------------------------------------------------------------------
def write_svh(path, rows, seed):
    """An `include file rather than a package, because it is meant to be
    pulled into an existing testbench package.  A standalone table would be
    better as a package: see the discussion in Chapter 9."""
    with open(path, "w") as f:
        f.write("// GENERATED by gen_vectors.py -- do not edit.\n")
        f.write(f"// seed={seed}  count={len(rows)}\n")
        f.write(f"localparam int unsigned VEC_COUNT = {len(rows)};\n")
        f.write("localparam logic signed [15:0] VEC_X0    [VEC_COUNT] = '{\n")
        f.write(",\n".join(f"  16'sh{x0 & 0xFFFF:04x}" for x0, _, _, _, _ in rows))
        f.write("};\n")
        f.write("localparam logic signed [15:0] VEC_Y0    [VEC_COUNT] = '{\n")
        f.write(",\n".join(f"  16'sh{y0 & 0xFFFF:04x}" for _, y0, _, _, _ in rows))
        f.write("};\n")
        f.write("localparam logic signed [15:0] VEC_THETA [VEC_COUNT] = '{\n")
        f.write(",\n".join(f"  16'sh{t & 0xFFFF:04x}" for _, _, t, _, _ in rows))
        f.write("};\n")
        f.write("localparam logic signed [15:0] VEC_XEXP  [VEC_COUNT] = '{\n")
        f.write(",\n".join(f"  16'sh{x & 0xFFFF:04x}" for _, _, _, x, _ in rows))
        f.write("};\n")
        f.write("localparam logic signed [15:0] VEC_YEXP  [VEC_COUNT] = '{\n")
        f.write(",\n".join(f"  16'sh{y & 0xFFFF:04x}" for _, _, _, _, y in rows))
        f.write("};\n")


# --------------------------------------------------------------------------
# The arctangent ROM, as generated source.
#
# cordic_pkg.sv computes this table with $atan in a constant function, which
# is the elegant way and works in Verilator and in the commercial tools.  It
# does NOT work in Icarus Verilog, which cannot return an unpacked array from
# a function, and some synthesis front ends are equally unhappy.  Generating
# the table from Python is the portable fallback, and it is the same technique
# you use for a register map or a coefficient set.
# --------------------------------------------------------------------------
def write_rom(path):
    with open(path, "w") as f:
        f.write("// GENERATED by gen_vectors.py -- do not edit.\n")
        f.write("// arctan(2**-i) in the internal angle format "
                f"(Q{m.IA - m.IQA - 1}.{m.IQA}), i = 0 .. {m.N - 1}\n")
        f.write(f"localparam iangle_t ATAN_ROM_GEN [{m.N}] = '{{\n")
        last = len(m.ATAN) - 1
        for i, v in enumerate(m.ATAN):
            sep = "" if i == last else ","
            f.write(f"  {m.IA}'sd{v}{sep:<2s}"
                    f"  // atan(2**-{i}) = {math.atan(2.0 ** -i):.9f} rad\n")
        f.write("};\n")


# --------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n", type=int, default=300, help="random transactions")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--out", default="../vectors/cordic_vectors.txt")
    ap.add_argument("--header", default=None)
    ap.add_argument("--svh", default=None)
    ap.add_argument("--rom", default=None)
    args = ap.parse_args()

    rows = build(args.n, args.seed)

    n = write_vectors(args.out, rows, args.seed)
    print(f"wrote {args.out}  ({n} vectors, seed {args.seed})")

    if args.header:
        write_header(args.header, rows, args.seed)
        print(f"wrote {args.header}")
    if args.svh:
        write_svh(args.svh, rows, args.seed)
        print(f"wrote {args.svh}")
    if args.rom:
        write_rom(args.rom)
        print(f"wrote {args.rom}")

    # A quick sanity check on the model itself, so that a broken model is
    # caught here rather than in a simulation three minutes later.
    worst = 0.0
    for x0, y0, th, x, y in rows:
        fx, fy = m.cordic_float(m.q_to_float(x0, m.QF),
                                m.q_to_float(y0, m.QF),
                                m.q_to_float(th, m.QA))
        worst = max(worst,
                    abs(x - fx * (1 << m.QF)), abs(y - fy * (1 << m.QF)))
    print(f"model self-check: worst deviation from the ideal rotation "
          f"= {worst:.2f} LSB")
    if worst > 8.0:
        print("model self-check FAILED", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
